name: Auto Create or Update PR

on:
  push:
    branches:
      [
        develop,
        feature/*,
        release/*,
        bugfix/*,
        hotfix/*,
        refactor/*,
        docs/*,
        chore/*,
      ]

jobs:
  auto_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create or Update PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSH_AUTHOR: ${{ github.actor }}
        run: |
          # 현재 브랜치 이름 가져오기
          CURRENT_BRANCH=$(echo $GITHUB_REF | sed 's|refs/heads/||')
          echo "현재 브랜치: $CURRENT_BRANCH"

          # 기존 PR이 있는지 확인
          EXISTING_PR=$(gh pr list --head "$CURRENT_BRANCH" --json number -q ".[0].number")

          # PR 템플릿 경로 설정
          PR_TEMPLATE_PATH=".github/pull_request_template.md"

          # PR Base 브랜치 설정
          if [[ "$CURRENT_BRANCH" == develop ]]; then
            BASE_BRANCH="main"
          else
            BASE_BRANCH="develop"
          fi

          # PR 템플릿 적용 여부 설정
          if [[ "$CURRENT_BRANCH" == docs/* || "$CURRENT_BRANCH" == chore/* ]]; then
            PR_BODY="> 변경 사항에 대해 간단히 서술해 주세요."
          else
            PR_BODY=$(cat "$PR_TEMPLATE_PATH")  
          fi

          if [ -z "$EXISTING_PR" ]; then
            echo "해당 브랜치에 대한 Pull Request가 없어요. 새로 생성합니다."
            gh pr create \
              --title "$CURRENT_BRANCH" \
              --body "$PR_BODY" \
              --assignee "$PUSH_AUTHOR" \
              --base "$BASE_BRANCH"
          else
            echo "이미 해당 브랜치에 대한 Pull Request가 있어요. 업데이트합니다."
            gh pr comment "$EXISTING_PR" --body "Branch updated with new changes."
          fi
